# Generated by Django 4.2.2 on 2023-07-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPackageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount_pirce', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('breakfast', models.CharField(blank=True, default='No', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='breakfast_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='discount_pirce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='package',
            field=models.ManyToManyField(blank=True, default=None, related_name='package_model', to='room.roompackagemodel'),
        ),
    ]
