# Generated by Django 4.2.2 on 2023-08-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_roompackagemodel_roomsmodel_breakfast_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsmodel',
            name='week_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='weekend_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
