# Generated by Django 4.2.2 on 2023-08-08 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_roomsmodel_week_price_roomsmodel_weekend_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_pirces', models.CharField(blank=True, default='room_prices', max_length=200, null=True)),
                ('room_only', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('room_breakfast', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('room_weekend', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('room_weeknd_breakfast', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('room_original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('room_original_breakfast', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='room_prices',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_prices', to='room.pricesmodel'),
        ),
    ]
