# Generated by Django 4.2.2 on 2023-08-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_pricesmodel_roomsmodel_room_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('room_pirce', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('breakfast', models.CharField(blank=True, default='No', max_length=200, null=True)),
                ('breakfast_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('firstName', models.CharField(blank=True, max_length=200, null=True)),
                ('lastName', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='room.roomsmodel')),
                ('user_dates', models.ManyToManyField(blank=True, default=None, related_name='userdates', to='room.reserveddates')),
            ],
        ),
    ]
