# Generated by Django 4.2.2 on 2023-08-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_reserveddates_reservedroommodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedroommodel',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservedroommodel',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
