# Generated by Django 4.2.2 on 2023-08-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_reserveddates_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedroommodel',
            name='breakfast_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reservedroommodel',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reservedroommodel',
            name='room_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
