# Generated by Django 4.2.2 on 2023-08-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_reservedroommodel_breakfast_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsmodel',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
