# Generated by Django 4.2.2 on 2023-07-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activitiesmodel_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesmodel',
            name='count_description',
            field=models.TextField(blank=True),
        ),
    ]
