# Generated by Django 4.2.2 on 2023-08-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activitiesmodel_count_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesmodel',
            name='count_down_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
