# Generated by Django 4.2.2 on 2023-07-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingcateredmodel_bookedmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedmodel',
            name='guests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookedmodel',
            name='status',
            field=models.CharField(blank=True, default='Cart', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookedmodel',
            name='uuid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookedmodel',
            name='check_in_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookedmodel',
            name='check_out_date',
            field=models.DateField(null=True),
        ),
    ]
