# Generated by Django 4.2.2 on 2023-07-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingcateredmodel_breakfastfee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcateredmodel',
            name='breakfast',
            field=models.CharField(blank=True, default='No', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookingcateredmodel',
            name='dinner',
            field=models.CharField(blank=True, default='No', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookingcateredmodel',
            name='lunch',
            field=models.CharField(blank=True, default='No', max_length=200, null=True),
        ),
    ]
